version: '3.8'

services:
  # PHP後端服務
  backend:
    image: php:8.2-apache
    container_name: travel_backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - db

  # MySQL資料庫
  db:
    image: mysql:8.0
    container_name: travel_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: travel_planner
      MYSQL_USER: traveluser
      MYSQL_PASSWORD: travelpass
    volumes:
      - db_data:/var/lib/mysql

  # phpMyAdmin（可選，方便管理資料庫）
  phpmyadmin:
    image: phpmyadmin
    container_name: travel_phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: traveluser
      PMA_PASSWORD: travelpass

  # 靜態前端服務
  frontend:
    image: nginx:alpine
    container_name: travel_frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend

volumes:
  db_data:
