services:
  backend:
    build: ./backend
    container_name: travel_backend
    ports:
      - "8010:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_HOST=db
      - DB_DATABASE=travel_planner
      - DB_USERNAME=traveluser
      - DB_PASSWORD=travelpass
    depends_on:
      - db

  # MySQL 資料庫
  db:
    image: mysql:8.0
    container_name: travel_db
    ports:
      - "3307:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: travel_planner
      MYSQL_USER: traveluser
      MYSQL_PASSWORD: travelpass
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: travel_phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: traveluser
      PMA_PASSWORD: travelpass

volumes:
  db_data:
